name: tp2
description: Código TP2 - Teoria de Algortimos FIUBA curso BUCHWALD 2023C2
version: 1.0.0
repository: https://github.com/MaximilianoCovela/TDA-TP2-2C2023

environment:
  sdk: ^3.1.0

dev_dependencies:
  test: ^1.21.0
